# Generated by Django 2.0 on 2020-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_id', models.CharField(max_length=10)),
                ('password', models.CharField(default='student', max_length=16)),
            ],
        ),
    ]
