# Generated by Django 2.0 on 2020-08-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(max_length=20)),
                ('attendance_percentage', models.CharField(max_length=3)),
                ('attendance_present', models.CharField(max_length=4)),
                ('attendance_total', models.CharField(max_length=4)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.login')),
            ],
        ),
        migrations.CreateModel(
            name='birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('marks', models.CharField(max_length=3)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.login')),
            ],
        ),
    ]
