# Generated by Django 2.0 on 2020-08-12 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_attendance_birthday_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
