# Generated by Django 2.0 on 2020-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_percentage',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.CharField(max_length=10),
        ),
    ]
