# Generated by Django 2.0 on 2020-08-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200812_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default='PRANJAL MAURYA', max_length=20),
            preserve_default=False,
        ),
    ]
