# Generated by Django 2.0 on 2020-08-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_teacher', models.CharField(max_length=40)),
                ('class_type', models.CharField(max_length=10)),
            ],
        ),
    ]
